package com.bookmap.plugin.rong.miniviteapp;

import com.bookmap.plugin.rong.miniviteapp.core.marketdata.PremarketVolume;
import com.bookmap.plugin.rong.miniviteapp.libraries.massive.Api;
import com.bookmap.plugin.rong.miniviteapp.models.Candle;
import com.bookmap.plugin.rong.miniviteapp.ports.HttpPort;
import com.bookmap.plugin.rong.miniviteapp.core.marketdata.MarketClock;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** Fixture expectations are generated by real TS library calls, not duplicated test calculations. */
class MassiveParityTest {
    @Test void agreesWithProductionTypeScript() throws Exception {
        JsonArray fixtures = JsonParser.parseReader(new InputStreamReader(
                getClass().getResourceAsStream("/massive-fixtures.json"), StandardCharsets.UTF_8)).getAsJsonArray();
        for (JsonElement element : fixtures) {
            JsonObject fixture = element.getAsJsonObject();
            String name = fixture.get("name").getAsString(), method = fixture.get("method").getAsString();
            JsonArray args = fixture.getAsJsonArray("args"), paths = new JsonArray();
            Api api = new Api((uri, verb, headers, body) -> {
                assertEquals("GET", verb); assertNull(body);
                assertTrue(uri.getRawQuery().contains("apiKey=fixture-secret-key"));
                String query = uri.getRawQuery().replaceAll("(^|&)apiKey=[^&]*", "").replaceAll("^&|&$", "");
                paths.add(uri.getRawPath() + (query.isEmpty() ? "" : "?" + query));
                JsonObject page = fixture.getAsJsonArray("pages").get(paths.size() - 1).getAsJsonObject();
                return new HttpPort.Response(page.get("status").getAsInt(), page.get("body").getAsString());
            }, () -> "fixture-secret-key");
            JsonElement result = null; String error = null;
            try {
                switch (method) {
                    case "getBars": result = candles(api.getBars(args.get(0).getAsString(), args.get(1).getAsString())); break;
                    case "getPriceHistory": result = candles(api.getPriceHistory(args.get(0).getAsString(), args.get(1).getAsInt(), args.get(2).getAsString())); break;
                    case "getPriceHistoryFromOldDateForHigherTimeframe": result = candles(api.getPriceHistoryFromOldDateForHigherTimeframe(args.get(0).getAsString(), args.get(1).getAsInt(), args.get(2).getAsString(), args.get(3).getAsString())); break;
                    case "getDailyCandlesForLastNDays": result = candles(api.getDailyCandlesForLastNDays(args.get(0).getAsString(), args.get(1).getAsInt(), args.get(2).getAsString())); break;
                    case "getSharesOutstanding": result = new com.google.gson.JsonPrimitive(api.getSharesOutstanding(args.get(0).getAsString())); break;
                    case "getTrades":
                        JsonArray trades = new JsonArray(); api.getTrades(args.get(0).getAsString(), args.get(1).getAsLong(), args.get(2).getAsLong()).forEach(trade -> trades.add(trade.toJson())); result = trades; break;
                    case "getFullPriceHistory": result = api.getFullPriceHistory(args.get(0).getAsString(), args.get(1).getAsString()); break;
                    case "calculatePremarketVolume": result = PremarketVolume.calculatePremarketVolume(parseCandles(args.get(0).getAsJsonArray())); break;
                    case "marketTime":
                        MarketClock.Time time = MarketClock.marketTime(args.get(0).getAsLong());
                        JsonObject json = new JsonObject(); json.addProperty("date", time.date);
                        json.addProperty("minutesSinceMarketOpen", time.minutesSinceMarketOpen);
                        json.addProperty("isPremarket", time.isPremarket); json.addProperty("isRegularSession", time.isRegularSession); result = json; break;
                    default: fail("Unknown scenario " + method);
                }
            } catch (Exception failure) { error = failure.getMessage(); }
            if (fixture.has("error")) { assertEquals(fixture.get("error").getAsString(), error, name); assertNull(result, name); }
            else { assertNull(error, name); assertEquals(fixture.get("result"), result, name); }
            if (fixture.has("paths")) assertEquals(fixture.get("paths"), paths, name);
        }
    }
    private static JsonArray candles(List<Candle> values) {
        JsonArray result = new JsonArray(); values.forEach(value -> result.add(value.toJson())); return result;
    }
    private static List<Candle> parseCandles(JsonArray values) {
        List<Candle> result = new ArrayList<>();
        for (JsonElement value : values) {
            JsonObject c = value.getAsJsonObject();
            result.add(new Candle(c.get("symbol").getAsString(), c.get("datetime").getAsLong(), c.get("open").getAsDouble(),
                    c.get("high").getAsDouble(), c.get("low").getAsDouble(), c.get("close").getAsDouble(), c.get("volume").getAsDouble(), c.get("vwap").getAsDouble()));
        }
        return result;
    }
}
